
/*----------  terrain lod headers  ----------*/


#define BUFFER_BINDING_TRANSFORMS 0
#define BUFFER_BINDING_GEOMETRY_VERTICES 1
#define BUFFER_BINDING_GEOMETRY_INDEXES 2
// #define BUFFER_BINDING_INSTANCED_GEOMETRY_VERTICES 6
// #define BUFFER_BINDING_INSTANCED_GEOMETRY_INDEXES 7
#define BUFFER_BINDING_INDIRECT_COMMAND 8
#define BUFFER_BINDING_SUBD1 3
#define BUFFER_BINDING_SUBD2 4
#define BUFFER_BINDING_CULLED_SUBD 5

#define BUFFER_BINDING_SUBD_COUNTER 0
#define BUFFER_BINDING_CULLED_SUBD_COUNTER 1


#define COMPUTE_THREAD_COUNT 32

#define threadGroupUpdateSize 16
#define FLAG_DISPLACE 1
#define FLAG_CULL 0
#define SHADING_DIFFUSE 1

/*----------  Indirect Headers  ----------*/
// #define BINDING_ATOMIC_COUNTER 0
// #define BINDING_ATOMIC_COUNTER2 1

// options
// #define ATOMIC_COUNTER_EXCHANGE_ARB 1
// #define UPDATE_INDIRECT_STRUCT 1
// #define UPDATE_INDIRECT_RESET_COUNTER1 1
// #define UPDATE_INDIRECT_RESET_COUNTER2 0
// #define UPDATE_INDIRECT_OFFSET 1
// #define UPDATE_INDIRECT_VALUE_DIVIDE 1
// #define UPDATE_INDIRECT_VALUE_ADD 0


